services:
  web:
    build: .
    command: ./bin/rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
      - DATABASE_HOST=diskstation.sea.mintrix.net
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=packmin2
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=packmin2
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
    volumes:
      - ./storage:/rails/storage
    restart: unless-stopped
